spring:
  application:
    name: feign-client-service

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
     getImage:
       execution:
         isolation:
           thread:
             timeoutInMilliseconds=2000