server:
  port: 2020
  
spring:  application:    name: api-gateway
    
info:
  app:
    name:@project.name@
    version:@project.version@
    encoding:@project.build.sourceEncoding@
  java:
      version:@java.version@

zuul:
  host:
    socket-timeout-millis: 2000000
  ribbon:
     eager-load:
      enabled: true
      
  routes:
    review-service:
       path: /review-service/**
       url: http://localhost:3434/      
       
management:  endpoints:    web:      exposure:        include:        - "*"        endpoint:    health:
     show-details: always