 server:
  port: 3434

 review-service:
     ribbon:
        eureka:
          enabled: false
     listOfServers: localhost:8770,localhost:8765
     ServerListRefreshInterval: 120000     
           
